#!/bin/sh

# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

VERSTR="Terragraph Uboot Version:"

grep -q -w \"u-boot\" /proc/mtd 2> /dev/null
if [ $? -eq 0 ]; then
	mtd_part=$(grep \"u-boot\" /proc/mtd | cut -f1 -d:)
	strings /dev/"${mtd_part}" | grep -i "${VERSTR}" | sed "s/.*\(${VERSTR}.*\)/\1/"
	exit 0
fi

