#
# Kbuild file for Terragraph kernel module qdisc pfifofc
#
ccflags-y += -I$(KERNEL_EXTRA_HEADER_PATH)/nl-driver-if \
	     -I$(srctree)/include/net -I.

# Disable new warnings
ccflags-y += -Werror

ifeq ($(ENABLE_ASAN),1)
	ccflags-y += -fsanitize=kernel-address
endif

MODULE_NAME ?= qdisc-pfifofc

obj-m := $(MODULE_NAME).o

# List of objects to compile, keep sorted
$(MODULE_NAME)-y := fb_qdisc_pfifofc.o

# Comment/uncomment the following line to disable/enable debugging
DEBUG = n
ifeq ($(DEBUG),y)
	DEBFLAGS = -O -g -DDEBUG # "-O" is needed to expand inlines
else
	DEBFLAGS = -O2
 endif

ccflags-y += $(DEBFLAGS)
