#!/bin/sh

# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# exit if no arg given
if [ $# -lt 1 ]; then
  exit 1
fi

TG_NODE_INFO_FILE=/var/run/node_info
# load node info file
if [ -f "$TG_NODE_INFO_FILE" ]; then
  . $TG_NODE_INFO_FILE
fi

# $1 is the env variable name
var_escaped=$(echo "$1" | sed 's/[^0-9A-Za-z_]//g')
eval echo "\$$var_escaped"
