#!/bin/sh

# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

dohelp() {
	echo "restart_e2e_minion [--retries numretries] [--stoponly]"
}

retries=1
while true; do
  case "$1" in
		-h | --help ) dohelp; exit 0; shift ;;
		-r | --retries ) retries=$2; shift; shift ;;
		-s | --stoponly ) stoponly=1; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

i=0
while [ "$i" -lt "$retries" ]; do
	if sv stop e2e_minion >/dev/null 2>/dev/null; then
		if [ -z "$stoponly" ]; then
			sv start e2e_minion >/dev/null 2>/dev/null
			exit $?
		fi
		exit 0
	fi
	i=$((i + 1))
	if [ "$i" -ne "$retries" ]; then
		sleep 1
	fi
done
exit 1
