#!/bin/sh

DELAY=10

while [ : ]; do

# load tg config environment variables
# shellcheck source=/dev/null
. /usr/sbin/config_get_env.sh

# check if firmware logging is enabled
if [ -z "$FW_LOGGING_ENABLED" ] || [ "$FW_LOGGING_ENABLED" -ne "1" ]; then
  echo "Firmware logging is not enabled"
  sleep ${DELAY}
  continue
fi

sv once start_host_manager_fw_log

exec /usr/bin/host_manager_11ad -d 2

done
