name: Check bitbake recipes

on:
  schedule:
    # weekly
    - cron: '0 1 * * 3'

jobs:
  build:
    name: Running python ${{ matrix.python-version }} on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run script
      run: >-
        python3 utils/check-bitbake-recipe-updates.py meta-* recipes-*
        --rewrite_git_url
        --fetch_timeout_s 60
        --skip_url /nxp-qoriq/u-boot
        --skip_url /nxp-qoriq/linux
        --skip_url erdgeist.org/opentracker
