name: Check for bitbake recipe updates

on: [push]

jobs:
  build:
    name: Running python ${{ matrix.python-version }} on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run script
      run: |
        python3 utils/check-bitbake-recipe-updates.py meta-* recipes-*
